### ISSUE TITLE
Tokenisation fails for some characters

### ISSUE THREAD

**Issue by lxs602** [KoichiYasuoka/IDSpiece#1]
Hi,

This is working well for most characters, but I have found that tokenisation occasionally fails:

```
>>> t=tokenize("𡿽")
>>> print(t)
['𡿽']

However:

user@user-pc:/usr/local/IDSpiece$ grep 𡿽.:  /usr/local/lib/python3.8/dist-packages/idspiece/cjk*.py
/usr/local/lib/python3.8/dist-packages/idspiece/cjk2.py:  #"𡿽":"⿰⿱⼺&GT-K00439;巛", # U+21FFD
```

More examples:

```
>>> t=tokenize("𡿸")
>>> print(t)
['𡿸']

user@user-pc:/usr/local/IDSpiece$ grep 𡿸.:  /usr/local/lib/python3.8/dist-packages/idspiece/cjk*.py
/usr/local/lib/python3.8/dist-packages/idspiece/cjk2.py:  #"𡿸":"⿱⼮⿱⼀囚", # U+21FF8]
```

```
>>> t=tokenize("𡿤")
>>> print(t)
['𡿤']

user@user-pc:/usr/local/IDSpiece$ grep 𡿤.:  /usr/local/lib/python3.8/dist-packages/idspiece/cjk*.py
/usr/local/lib/python3.8/dist-packages/idspiece/cjk2.py:  #"𡿤":"⿰⿱⿳卝八日⿱⼋土⿳山口⿱⼭口", # U+21FE4
```

Thanks,

L

**Comment by KoichiYasuoka** [comment]
Thank you for the information, and I've just updated 𡿽 as ['⿰⾡',' 巛']. But I could not change others because of the IDSpiece rules:

* Only nine IDCs (U+2FF0, U+2FF1, U+2FF4 to U+2FFA) are used.
* IDCs never occur instantly after another IDC.
* Instantly after IDCs, Kanxi Radicals and Supplement (U+2E80 to U+2FD5) are preferred.
* Otherwise, CJK Unified Ideographs and Extension A (U+3400 to U+9FFC) are preferred.

**Comment by lxs602** [comment]
You would reasonably be expected to give your aims for the project, as you have made it public.

You have not explained your choice of IDSpiece rules. 

It has also not been stated that the project does not fully tokenise.

**Comment by KoichiYasuoka** [comment]
Well @lxs602 I recommend you to read [Basic usage](https://github.com/KoichiYasuoka/IDSpiece#basic-usage) more precisely, especially in the line

```py
...       text=idstable[c][2]+text[1:]
```

and try to understand what it aims.

**Comment by lxs602** [comment]
https://github.com/KoichiYasuoka/IDSpiece/issues/2#issuecomment-1008164195

**Comment by KoichiYasuoka** [comment]
Well @lxs602 I wrote at https://github.com/KoichiYasuoka/IDSpiece/issues/2#issuecomment-1007083561 the aims of my project, but not the aims of my program itself. Have you already understood my aim of the program of IDSpiece? Especially in the line

```py
...       text=idstable[c][2]+text[1:]
```

how about it?

**Comment by lxs602** [comment]
The code appears to resolve characters iteratively, using the second character after each term as the term for the next search. It would be consistent with your requirement for there to be no IDC immediately after another IDC.

The code is only the mechanism, and not the aims of the programme, which you have given [here](https://github.com/KoichiYasuoka/IDSpiece/blob/main/setup.py#L9). As it does not yet fully tokenise some Chinese characters, such as 𡿸 and 𡿤 above, perhaps the aims have not yet been met, to explain my comments [above](https://github.com/KoichiYasuoka/IDSpiece/issues/1#issuecomment-1006649138).

The programme has been contributed to the public on [pypi](https://pypi.org/project/idspiece/) and on pip. It is appropriate to briefly explain the background or rationale for the programme, and any future plans. For example, any plans to rewrite definitions of characters that are not tokenised, such as 𡿽 above, to meet the rules. Alternatively, if you may change the rules (and the code), as you are the author of the project. If they are fixed for research, it would be interesting to link to a research paper which explains them. I am sorry that I do not speak Japanese, but auto-translation is usually helpful.

CHISE has been incorporated into several projects, such as [cjklib](https://github.com/cburgmer/cjklib/blob/3faf249e1416ed5dca4d7b9a3341400bf64a9e50/scripts/convertdecomposition.py#L21) and on into [makemeahanzi](https://github.com/skishore/makemeahanzi/blob/master/README.md#dictionarytxt-keys), and I hope that the interest from the general public is encouraging.

**Comment by KoichiYasuoka** [comment]
Well @lxs602 

> The code is only the mechanism, and not the aims of the programme

sorry but I'm afraid that you seem not to have learned "Right-Linear Grammar".

**Comment by lxs602** [comment]
Your mistake is in your understanding of **human** language.

You are confused on what I mean.

If you do not understand, ask someone else to explain it to you.

Read this on the "theory of four causes" by Aristotle:

https://ja.wikipedia.org/wiki/%E5%9B%9B%E5%8E%9F%E5%9B%A0%E8%AA%AC

https://www.rei-yumesaki.net/%E5%93%B2%E5%AD%A6/%E5%93%B2%E5%AD%A6-%E5%80%AB%E7%90%86%E5%AD%A6/%E5%9B%9B%E5%8E%9F%E5%9B%A0%E8%AA%AC/

To apply the above theory to what is the purpose / mission / aim / goal of the programme:

![149587404-b2bbc711-9e32-41a8-942b-071a15589428](https://user-images.githubusercontent.com/44102215/149598985-de121422-d743-40c6-a4dd-8f7481ddd0c5.png)

**Comment by lxs602** [comment]
Why have you ignored [my comments](https://github.com/KoichiYasuoka/IDSpiece/issues/1#issuecomment-1010969676)? I am trying to help you.

Your documentation is inadequate. 

> 神を敬う人からのきびしい忠告は、
> 私を思う心から出たものです。
> 非難されたように感じても、
> 私にとって薬となるのです。
> 私が彼らの非難を拒絶することがありませんように。 （詩篇141：5）

**Comment by KoichiYasuoka** [comment]
Yes @lxs602 so, at first, I'm explaining my aim of "[Basic usage](https://github.com/KoichiYasuoka/IDSpiece#basic-usage)" one by one, confirming your understanding of the program. Then, after that, I think I can tell you about my aim of the whole program (including extended usages) itself. Please don't hurry up. Now, how about your understanding of "Right-Linear Grammar"?

**Comment by lxs602** [comment]
>text=idstable[c][2]+text[1:]

The first two characters are terminal, and on the right-hand side, the third character, is non-terminal. On resolution, the next character in the input string is then used.

This is obvious from the output, e.g. tokenize(𤂍@)  :
> 𤂍 -> ⿰⺡蓮
> 蓮 -> ⿱⺾連
> 連 -> ⿺⻌車
> 車 -> 車
> @ -> @

Hence, 
> tokens = ⿰⺡, ⿱⺾, ⿺⻌, 車, @

I am happy to list my understanding of each rule. 

However, I am not a computer scientist or a linguist.

**Comment by lxs602** [comment]
This conversation has been at "cross-purposes". 

For example, if a poet and a meteorologist look at a sunset, they will see different things. When they talk, they may not understand each other. 

Hence, my statement "The code is only the mechanism, and not the aims of the programme" is philosophical. I attempted to explain this [here](https://github.com/KoichiYasuoka/IDSpiece/issues/1#issuecomment-1013483405). Aristotle's theory shows that we see purpose differently.

No offence is meant by the picture, as "A picture is worth a thousand words".

Be aware that when you do not respond to others, it looks like an attempt to dismiss criticism, hence this [comment](https://github.com/KoichiYasuoka/IDSpiece/issues/1#issuecomment-1013502832) and the Bible reference.

**Comment by KoichiYasuoka** [comment]
> The first two characters are terminal, and on the right-hand side, the third character, is non-terminal. On resolution, the next character in the input string is then used.

OK, now you @lxs602 seem to have learned Right-Linear Grammar. Then, we shall go beyond (outside of) Right-Linear Grammar, but

> However, I am not a computer scientist or a linguist.

oh it's a bad news. Here I recommend you, at least, to learn PushDown Automaton, while I realize that it's too early to step up to LL(k)-Grammar or some other grammars... Umm...

Well, we stay inside Right-Linear Grammar in this comment and try to extend "[Basic usage](https://github.com/KoichiYasuoka/IDSpiece#basic-usage)" especially in the line:

```
...     if c in idstable:
```

with your example "𤂍@" above. In "Basic usage" we see that `idstable` is used as the set of non-terminal tokens, and we can easily expand (or shrink) it with another algebraic closure of non-terminal tokens. For example

```py
>>> from idspiece import idstable
>>> t={"連"}
>>> closure={k for k,v in idstable.items() if v[2] in t}
>>> while closure!=t:
...   t=closure
...   closure={k for k,v in idstable.items() if k in t or v[2] in t}
...
>>> def tokenize(text):
...   tokens=[]
...   while text>"":
...     c=text[0]
...     if c in closure:
...       tokens.append(idstable[c][0:2])
...       text=idstable[c][2]+text[1:]
...     else:
...       tokens.append(c)
...       text=text[1:]
...   return tokens
...
>>> t=tokenize("𤂍@")
>>> print(t)
```

oops, ah well, @lxs602 do you understand this kind of `closure`? What does it consist of? How is it used?
