### ISSUE TITLE
CJKVI-ids-unicode - more fully resolved sequences

### ISSUE THREAD

**Issue by lxs602** [KoichiYasuoka/IDSpiece#2]
Hi,

I have found the project below, which further resolves many of the entity references still remaining in cjkvi-ids.

It has not gained much notice, but I hope it would be useful for your project.

https://transfusion.github.io/cjkvi-ids-unicode

See also:
https://github.com/Transfusion/cjkvi-ids-unicode

Regards,

L

**Comment by KoichiYasuoka** [comment]
Thank you for the information, but I only use [CHISE-IDS](https://www.chise.org/ids/).

**Comment by lxs602** [comment]
You have not given an explanation of your choice.

The project linked to is CHISE-IDS, with algortihmic replacement of many entity references.

Your project is not as useful as it could be, as you are neglecting other available resources.

**Comment by KoichiYasuoka** [comment]
Umm... Sorry @lxs602 but I cannot understand what you mean. The CHISE-IDS is one of the projects of my department (Center for Informatics in East Asian Studies, Institute for Research in Humanities) of Kyoto University. I understand that https://transfusion.github.io/cjkvi-ids-unicode is a very good project, but its "Substituting heuristic" seems too tentative and is not applicable to IDSpiece.

**Comment by lxs602** [comment]
Your response does clarify your aims. It would not be appropriate to use an amateur project such as [cjkvi-ids-unicode](https://transfusion.github.io/cjkvi-ids-unicode) in research.

To benefit learners of East Asian languages, who do not need the same standards of accuracy, I have made a simple fork using the above project.

Best wishes for your research.
